DATA:
  TOUCHPAIR:
    TRAIN:
      PAIR_LIST: "./data/train/chair/train_chair_adjacent_pairs.pickle"
    TEST:
      PAIR_LIST: "./data/test/bed/test_beds_adjacent_pairs.pickle"
      IMG_HEIGHT: 256
      IMG_WIDTH: 256
  NUM_WORKERS: 4
MODEL:
  CHOICE: 'JointNet'
SCHEDULER:
  TYPE: "StepLR"
  MAX_EPOCH: 60
  StepLR:
    gamma: 0.9
    step_size: 2
SOLVER:
  TYPE: "Adam"
  BASE_LR: 0.001
TRAIN:
  BATCH_SIZE: 64
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 10
  VAL_PERIOD: 0
TEST:
  BATCH_SIZE: 1
  LOG_PERIOD: 1
  WEIGHT: './outputs/JointNet/joint_model.pth'





