DATA:
  PART:
    TRAIN:
      IMG_DIR: './data/train/chair'
      PART_LIST: 'train_chair_parts.pickle'
      IMG_HEIGHT: 256
      IMG_WIDTH: 256
      MASK_PREFIX: 'partmask'
    TEST:
      IMG_DIR: './data/test/bed'  # path to rendered image directory
      SHAPE_LIST: 'test_beds.txt'
      IMG_HEIGHT: 256
      IMG_WIDTH: 256
      MASK_PREFIX: 'partmask'
  NUM_WORKERS: 4
MODEL:
  CHOICE: 'RotNet'
  ROTNET:
    NET_OPTION: "MixQuat"
    IMG_OPTION: "conca"
    RELATIVE_SIZE: False
    ORTHONORMAL: False
    METRIC: "RotGTSize"
    LOSS: "MixMinNEMD-0.1"
SCHEDULER:
  TYPE: "StepLR"
  MAX_EPOCH: 20
  StepLR:
    gamma: 0.7
    step_size: 2
SOLVER:
  TYPE: "Adam"
  BASE_LR: 0.001
TRAIN:
  BATCH_SIZE: 64
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 20
  VAL_PERIOD: 0
TEST:
  BATCH_SIZE: 1
  WEIGHT: "./outputs/RotNet/rotnet_model.pth"
  LOG_PERIOD: 1



